name: "flexopus-auto-parking"

services:
  booking-niklas:
    image: "ghcr.io/nimarion/flexopus-auto-parking:main"
    restart: "no"
    environment:
      - FLEXOPUS_COOKIE_FILE=/cookies/niklas-cookie.pkl
    env_file:
      - ${PWD}/.env
    volumes:
      - ${PWD}/cookies:/cookies
    command: ["--prefered-parking-spaces", "Parking 54"]
  booking-max:
    image: "ghcr.io/nimarion/flexopus-auto-parking:main"
    restart: "no"
    environment:
      - FLEXOPUS_COOKIE_FILE=/cookies/max-cookie.pkl
    env_file:
      - ${PWD}/.env
    volumes:
      - ${PWD}/cookies:/cookies
    command: ["--prefered-parking-spaces", "Parking 66", "Parking 32"]